# Site settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Site
name: Junteng Liu
title: Junteng Liu
description: PhD Candidate at HKUST NLP Group

# URL
baseurl: ""
url: "https://stoophandoms.github.io"

# About/contact
author:
  name: Junteng Liu
  email: jliugi@connect.ust.hk

# Social links
github: Vicent0205
googlescholar: "tbK9jl4AAAAJ"
twitter: junteng88716710

# Build settings
theme: minima
markdown: kramdown
permalink: /:title/